import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "None"

[font]
normal = { family = "CaskaydiaCove Nerd Font" }
size = 10.25

[selection]
save_to_clipboard = true

